package com.autonomousone.messages

import com.autonomousone.messages.data.MessagesDatabase
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Guards the hand-written v3 → v4 migration against the schema Room actually
 * expects (app/schemas/.../4.json, generated by KSP). If the migration drifts
 * from the generated schema, Room throws on the device at upgrade time — this
 * test catches that drift on every `testDebugUnitTest` run.
 */
class MigrationV3V4SqlTest {

    private fun schemaJson(): String {
        val file = File(
            "schemas/com.autonomousone.messages.data.MessagesDatabase/4.json"
        )
        if (!file.exists()) {
            fail("Schema 4.json not found at ${file.absolutePath} — run :app:kspDebugKotlin")
        }
        return file.readText()
    }

    private fun compact(sql: String): String = sql.filterNot { it.isWhitespace() }

    /**
     * All CREATE statements the generated schema expects, resolved from
     * Room's `${TABLE_NAME}` placeholder to the concrete table name.
     */
    private fun schemaStatements(): Set<String> {
        val json = schemaJson()
        return Regex("\"CREATE[^\"]*\"")
            .findAll(json)
            .map { it.value.removeSurrounding("\"") }
            .map { stmt ->
                // Room writes `ON `${TABLE_NAME}`` — the placeholder is already
                // surrounded by backticks, so the replacement is the BARE name.
                when {
                    stmt.contains("USING FTS4") ->
                        stmt.replace("\${TABLE_NAME}", "messages_fts")
                    stmt.contains("index_conversations_lastMessageDate") ->
                        stmt.replace("\${TABLE_NAME}", "conversations")
                    else ->
                        stmt.replace("\${TABLE_NAME}", "messages")
                }
            }
            .map(::compact)
            .toSet()
    }

    @Test
    fun `every non-drop migration statement matches the generated v4 schema`() {
        val expected = schemaStatements()

        MessagesDatabase.MIGRATION_3_4_SQL
            .filterNot { it.startsWith("DROP", ignoreCase = true) }
            .forEach { statement ->
                assertTrue(
                    "Migration statement not in generated 4.json schema:\n$statement\n(Run :app:kspDebugKotlin and compare app/schemas/.../4.json)",
                    compact(statement) in expected
                )
            }
    }

    @Test
    fun `migration drops the legacy non-managed indexes`() {
        val statements = MessagesDatabase.MIGRATION_3_4_SQL.map(::compact)
        assertTrue(statements.contains("DROPINDEXIFEXISTS`idx_messages_thread_unread`"))
        assertTrue(statements.contains("DROPINDEXIFEXISTS`idx_messages_thread_date_id`"))
    }

    @Test
    fun `generated schema declares the four FTS content-sync triggers`() {
        val json = schemaJson()
        listOf(
            "room_fts_content_sync_messages_fts_BEFORE_UPDATE",
            "room_fts_content_sync_messages_fts_BEFORE_DELETE",
            "room_fts_content_sync_messages_fts_AFTER_UPDATE",
            "room_fts_content_sync_messages_fts_AFTER_INSERT"
        ).forEach { name ->
            assertTrue("Schema is missing trigger $name", json.contains(name))
        }
        assertTrue(json.contains("\"contentTable\": \"messages\""))
    }
}
