package com.autonomousone.messages

import com.autonomousone.messages.data.MessagesDatabase
import org.junit.Assert.assertTrue
import org.junit.Assert.assertEquals
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Guards the hand-written migrations (v2 → v4 and v3 → v4) against the schema
 * Room actually expects (app/schemas/.../4.json, generated by KSP). If a
 * migration drifts from the generated schema, Room throws on the device at
 * upgrade time — this test catches that drift on every `testDebugUnitTest` run.
 *
 * Also guards the data-preserving sync_state rebuild: upgrading must NEVER
 * silently drop watermarks again (that made every app update a 360K rescan).
 */
class MigrationToV4SqlTest {

    private fun schemaJson(): String {
        val file = File(
            "schemas/com.autonomousone.messages.data.MessagesDatabase/4.json"
        )
        if (!file.exists()) {
            fail("Schema 4.json not found at ${file.absolutePath} — run :app:kspDebugKotlin")
        }
        return file.readText()
    }

    private fun compact(sql: String): String = sql.filterNot { it.isWhitespace() }

    /**
     * All CREATE statements the generated schema expects, resolved from
     * Room's `${TABLE_NAME}` placeholder to the concrete table name.
     */
    private fun schemaStatements(): Set<String> {
        val json = schemaJson()
        return Regex("\"CREATE[^\"]*\"")
            .findAll(json)
            .map { it.value.removeSurrounding("\"") }
            .map { stmt ->
                val table = when {
                    stmt.contains("USING FTS4") -> "messages_fts"
                    stmt.contains("index_conversations_lastMessageDate") -> "conversations"
                    stmt.contains("`newestDate`") -> "sync_state"
                    stmt.contains("`snippet`") -> "conversations"
                    else -> "messages"
                }
                stmt.replace("\${TABLE_NAME}", table)
            }
            .map(::compact)
            .toSet()
    }

    private val v4CreateSync = schemaStatements().first {
        it.startsWith("CREATETABLEIFNOTEXISTS`sync_state`")
    }

    @Test
    fun `every non-drop migration statement matches the generated v4 schema`() {
        val expected = schemaStatements()

        MessagesDatabase.UPGRADE_TO_V4_SQL
            .filterNot { it.startsWith("DROP", ignoreCase = true) }
            .forEach { statement ->
                assertTrue(
                    "Migration statement not in generated 4.json schema:\n$statement\n(Run :app:kspDebugKotlin and compare app/schemas/.../4.json)",
                    compact(statement) in expected
                )
            }
    }

    @Test
    fun `UPGRADE list never drops sync_state`() {
        // The blanket DROP was the P0: it erased watermarks on every upgrade.
        assertTrue(
            "sync_state must be migrated data-preservingly, never blanket-dropped",
            MessagesDatabase.UPGRADE_TO_V4_SQL.none {
                compact(it).startsWith("DROPTABLE") && it.contains("sync_state")
            }
        )
    }

    @Test
    fun `a database already in exact v4 shape is left untouched`() {
        val sql = MessagesDatabase.syncStateRebuildSql(MessagesDatabase.V4_SYNC_COLUMNS)
        assertTrue("Exact-v4 tables must not be rebuilt at all", sql.isEmpty())
    }

    private val v2Columns = setOf("source", "newestSyncedDate", "backfillComplete", "lastSyncAt")

    @Test
    fun `legacy v2 shape is rebuilt via copy and rename, not a plain drop`() {
        val sql = MessagesDatabase.syncStateRebuildSql(v2Columns)
        val joined = compact(sql.joinToString(" "))

        // Standard Room rebuild: new table → INSERT..SELECT → DROP old → RENAME.
        assertTrue(joined.contains("CREATETABLE`sync_state_v4_new`"))
        assertTrue(joined.contains("INSERTINTO`sync_state_v4_new`"))
        assertTrue(joined.contains("FROM`sync_state`"))
        assertTrue(joined.contains("DROPTABLE`sync_state`"))
        assertTrue(joined.contains("ALTERTABLE`sync_state_v4_new`RENAMETO`sync_state`"))
        // The final table must carry the exact v4 column set.
        val create = compact(sql.first { it.contains("sync_state_v4_new") })
        MessagesDatabase.V4_SYNC_COLUMNS.forEach { col ->
            assertTrue("v4 column `$col` missing from rebuild", create.contains("`$col`"))
        }
        assertTrue(!create.contains("newestSyncedDate"))
    }

    @Test
    fun `v2 copy maps legacy columns to the v4 fields`() {
        val sql = MessagesDatabase.syncStateRebuildSql(v2Columns)
        val insert = sql.first { it.startsWith("INSERT INTO") }
        assertTrue("newestDate ← newestSyncedDate", insert.contains("`newestSyncedDate`"))
        assertTrue("lastReconcileAt ← lastSyncAt", insert.contains("`lastSyncAt`"))
        assertTrue("historyBackfillComplete ← backfillComplete", insert.contains("`backfillComplete`"))
        assertTrue("initialWindowReady pinned to 1", insert.contains(", 1,"))
    }

    @Test
    fun `broken 2-to-3 hybrid keeps any newestDate already ALTERed in when legacy is stale`() {
        val hybrid = v2Columns + setOf(
            "newestDate", "newestId", "oldestDate", "oldestId",
            "initialWindowReady", "historyBackfillComplete", "lastReconcileAt", "schemaVersion"
        )
        val sql = MessagesDatabase.syncStateRebuildSql(hybrid)
        val insert = sql.first { it.startsWith("INSERT INTO") }
        assertTrue("prefers newestSyncedDate when > 0", insert.contains("CASE WHEN `newestSyncedDate` > 0"))
        assertTrue("falls back to ALTER-added newestDate", insert.contains("IFNULL(`newestDate`, 0)"))
    }

    @Test
    fun `unknown non-v4 shape falls back to drop and recreate`() {
        val sql = MessagesDatabase.syncStateRebuildSql(setOf("source", "weird"))
        assertEquals(2, sql.size)
        assertEquals("DROP TABLE IF EXISTS `sync_state`", sql[0])
        assertEquals(v4CreateSync, compact(sql[1]))
    }

    @Test
    fun `missing table is created plain v4`() {
        val sql = MessagesDatabase.syncStateRebuildSql(emptySet())
        assertEquals(1, sql.size)
        assertEquals(v4CreateSync, compact(sql[0]))
    }

    @Test
    fun `migration drops the legacy non-managed indexes`() {
        val statements = MessagesDatabase.UPGRADE_TO_V4_SQL.map(::compact)
        assertTrue(statements.contains("DROPINDEXIFEXISTS`idx_messages_thread_unread`"))
        assertTrue(statements.contains("DROPINDEXIFEXISTS`idx_messages_thread_date_id`"))
    }

    @Test
    fun `both upgrade paths exist and target v4`() {
        assertEquals(2, MessagesDatabase.MIGRATION_2_4.startVersion)
        assertEquals(4, MessagesDatabase.MIGRATION_2_4.endVersion)
        assertEquals(3, MessagesDatabase.MIGRATION_3_4.startVersion)
        assertEquals(4, MessagesDatabase.MIGRATION_3_4.endVersion)
    }

    @Test
    fun `generated schema declares the four FTS content-sync triggers`() {
        val json = schemaJson()
        listOf(
            "room_fts_content_sync_messages_fts_BEFORE_UPDATE",
            "room_fts_content_sync_messages_fts_BEFORE_DELETE",
            "room_fts_content_sync_messages_fts_AFTER_UPDATE",
            "room_fts_content_sync_messages_fts_AFTER_INSERT"
        ).forEach { name ->
            assertTrue("Schema is missing trigger $name", json.contains(name))
        }
        assertTrue(json.contains("\"contentTable\": \"messages\""))
    }
}
