package com.autonomousone.messages

import com.autonomousone.messages.data.MessagesDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Guards MIGRATION_5_6 (conversations.lastMessageType) against the schema
 * Room actually expects (app/schemas/.../6.json, generated by KSP) and
 * against removing the newest-wins guard from the upsert statement.
 */
class MigrationToV6SqlTest {

    private fun compact(sql: String): String = sql.filterNot { it.isWhitespace() }

    private fun schemaJson(): String {
        val file = File("schemas/com.autonomousone.messages.data.MessagesDatabase/6.json")
        if (!file.exists()) {
            fail("Schema 6.json not found at ${file.absolutePath} — run :app:kspDebugKotlin")
        }
        return file.readText()
    }

    @Test
    fun `migration declares the 5 to 6 boundary`() {
        assertEquals(5, MessagesDatabase.MIGRATION_5_6.startVersion)
        assertEquals(6, MessagesDatabase.MIGRATION_5_6.endVersion)
    }

    @Test
    fun `v6 migration is additive only - never drops or rebuilds conversations`() {
        val statements = MessagesDatabase.UPGRADE_TO_V6_SQL
        assertTrue(
            "v6 must be an ADD COLUMN + UPDATE backfill, no table rebuilds",
            statements.none {
                compact(it).startsWith("DROPTABLE") || compact(it).startsWith("CREATETABLE")
            }
        )
        assertTrue(
            statements.first().startsWith("ALTER TABLE `conversations` ADD COLUMN"),
        )
    }

    @Test
    fun `added column matches the generated schema six json`() {
        val json = schemaJson()
        assertTrue(
            "6.json must declare lastMessageType INTEGER NOT NULL",
            json.contains("\"fieldPath\": \"lastMessageType\"") &&
            json.contains("\"columnName\": \"lastMessageType\"")
        )
        val create = Regex("\"CREATE TABLE IF NOT EXISTS `\\$\\{TABLE_NAME\\}` \\(`threadId`[^\"]*\"")
            .find(json)!!.value.removeSurrounding("\"")
        assertTrue("column order: lastMessageType before pinned", create.indexOf("lastMessageType") < create.indexOf("`pinned`"))
        assertTrue("column is INTEGER NOT NULL", create.contains("`lastMessageType` INTEGER NOT NULL"))
    }

    @Test
    fun `backfill picks the newest message with the deterministic provider tie-break`() {
        val update = MessagesDatabase.UPGRADE_TO_V6_SQL.last()
        val c = compact(update)
        assertTrue("reads type from messages", c.contains("SELECTtypeFROMmessages"))
        assertTrue(
            "deterministic newest-row tie (date DESC, source DESC, providerId DESC)",
            c.lowercase().contains("orderbydatedesc,sourcedesc,provideriddesc")
        )
        assertTrue("bounded LIMIT 1", c.contains("LIMIT1"))
        assertTrue(
            "threads with no messages keep the DEFAULT (WHERE EXISTS guard)",
            c.contains("WHEREEXISTS")
        )
    }

    @Test
    fun `default value keeps legacy rows incoming`() {
        val alter = MessagesDatabase.UPGRADE_TO_V6_SQL.first()
        assertTrue(alter.contains("DEFAULT 1"))
    }
}
